// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFN2h65W37a3jmhtp4e-kde0AKNZxtUzs',
    appId: '1:494783918856:web:c9c8446a8cdb6476e2b2bd',
    messagingSenderId: '494783918856',
    projectId: 'test2-1606d',
    authDomain: 'test2-1606d.firebaseapp.com',
    storageBucket: 'test2-1606d.appspot.com',
    measurementId: 'G-B7V58Q8ZBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADbm05YPKf6hqoGcbtMb9JYdezwgb23j0',
    appId: '1:494783918856:android:3078c7d5a4eab8d0e2b2bd',
    messagingSenderId: '494783918856',
    projectId: 'test2-1606d',
    storageBucket: 'test2-1606d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGjjQ4Zw1gwRx9pn0nVETmSaVpYGSy7N4',
    appId: '1:494783918856:ios:81d6fd92fd9ec0a5e2b2bd',
    messagingSenderId: '494783918856',
    projectId: 'test2-1606d',
    storageBucket: 'test2-1606d.appspot.com',
    iosBundleId: 'com.example.playground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGjjQ4Zw1gwRx9pn0nVETmSaVpYGSy7N4',
    appId: '1:494783918856:ios:2c36911541ec36f2e2b2bd',
    messagingSenderId: '494783918856',
    projectId: 'test2-1606d',
    storageBucket: 'test2-1606d.appspot.com',
    iosBundleId: 'com.example.playground.RunnerTests',
  );
}
